### ISSUE TITLE
"ListCache<> could not be found"

### ISSUE THREAD

**Issue by LesBonsOeufs** [cakeslice/FishyWebRTC#4]
There is information on this here:
https://fish-networking.gitbook.io/docs/manual/general/changelog/break-solutions
![image](https://github.com/user-attachments/assets/abfb096d-7136-4f61-82ee-02443fda0d67)

But it isn't clear.
Which of these 4 classes must I use?
Each of them is a static class and cannot be used as an instance (which is what is needed in FishyWebRTC).

Any help would be appreciated.

**Comment by cakeslice** [comment]
Not sure, I made this for a previous version of FishNetworking and for now I don't plan to support the newer ones.

You could try to get help from their Discord.

**Comment by LesBonsOeufs** [comment]
Simply replacing by usual List<T> works
